# Generated by Django 5.0.2 on 2024-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='pravin',
        ),
    ]
