# Generated by Django 5.0.2 on 2024-03-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_my_details_delete_mobiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_details',
            old_name='cell',
            new_name='phone',
        ),
    ]
