# Generated by Django 5.0.2 on 2024-03-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_profile_delete_my_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
