# Generated by Django 5.0.2 on 2024-03-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('stu_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('class_sec', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
