# Generated by Django 5.0.2 on 2024-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_city_delete_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
